def menu():
    print("\n--- CLIENTES ---")
    print("1 - Cadastrar Cliente")
    print("2 - Listar Clientes")
    print("3 - Procurar Cliente")
    print("--- AGENCIAS ---")
    print("4 - Cadastrar Agencia")
    print("5 - Listar Agencias")
    print("6 - Procurar Agencia")
    print("--- CONTAS ---")
    print("7 - Cadastrar Conta")
    print("8 - Listar Contas")
    print("--- OPERACOES ---")
    print("9 - Consultar Saldo")
    print("10 - Depositar")
    print("11 - Sacar")
    print("12 - Transferir")
    print("--- RELATORIOS E SISTEMA ---")
    print("13 - Relatorio do banco")
    print("14 - Montante total por agencia")
    print("15 - Montante total do banco")
    print("16 - Salvar")
    print("0 - Sair")