def menu():
    print("\nCLIENTES: ")
    print("1 - Cadastrar cliente")
    print("2 - Listar clientes")
    print("3 - Procurar cliente")
    print("AGENCIAS:")
    print("4 - Cadastrar agencia")
    print("5 - Listar agencias")
    print("6 - Procurar agencia")
    print("CONTAS:")
    print("7 - Cadastrar conta")
    print("8 - Listar contas")
    print("OPERACOES:")
    print("9 - Consultar saldo")
    print("10 - Depositar")
    print("11 - Sacar")
    print("12 - Transferir")
    print("0 - Sair")